process {
  version: 'v18.1.0',
    versions: {
    node: '18.1.0',
      v8: '10.1.124.8-node.13',
        uv: '1.43.0',
          zlib: '1.2.11',
            brotli: '1.0.9',
              ares: '1.18.1',
                modules: '108',
                  nghttp2: '1.47.0',
                    napi: '8',
                      llhttp: '6.0.4',
                        openssl: '3.0.2+quic',
                          cldr: '41.0',
                            icu: '71.1',
                              tz: '2022a',
                                unicode: '14.0',
                                  ngtcp2: '0.1.0-DEV',
                                    nghttp3: '0.1.0-DEV'
  },
  arch: 'x64',
    platform: 'win32',
      release: {
    name: 'node',
      sourceUrl: 'https://nodejs.org/download/release/v18.1.0/node-v18.1.0.tar.gz',
        headersUrl: 'https://nodejs.org/download/release/v18.1.0/node-v18.1.0-headers.tar.gz',
          libUrl: 'https://nodejs.org/download/release/v18.1.0/win-x64/node.lib'
  },
  _rawDebug: [Function: _rawDebug],
    moduleLoadList: [
      'Internal Binding native_module',
      'Internal Binding errors',
      'NativeModule internal/errors',
      'Internal Binding config',
      'Internal Binding timers',
      'Internal Binding async_wrap',
      'Internal Binding constants',
      'Internal Binding util',
      'Internal Binding types',
      'NativeModule internal/util',
      'NativeModule internal/util/types',
      'NativeModule internal/validators',
      'NativeModule internal/promise_hooks',
      'Internal Binding task_queue',
      'Internal Binding symbols',
      'NativeModule internal/async_hooks',
      'NativeModule internal/linkedlist',
      'NativeModule internal/priority_queue',
      'NativeModule internal/assert',
      'Internal Binding icu',
      'NativeModule internal/util/inspect',
      'NativeModule internal/util/debuglog',
      'NativeModule internal/timers',
      'NativeModule events',
      'Internal Binding buffer',
      'Internal Binding string_decoder',
      'NativeModule internal/buffer',
      'Internal Binding blob',
      'NativeModule internal/encoding',
      'Internal Binding messaging',
      'NativeModule internal/worker/js_transferable',
      'NativeModule internal/constants',
      'NativeModule internal/blob',
      'NativeModule buffer',
      'NativeModule internal/modules/esm/handle_process_exit',
      'Internal Binding process_methods',
      'NativeModule internal/process/per_thread',
      'Internal Binding credentials',
      'NativeModule internal/process/promises',
      'NativeModule internal/fixed_queue',
      'NativeModule async_hooks',
      'NativeModule internal/process/task_queues',
      'Internal Binding worker',
      'NativeModule util',
      'Internal Binding performance',
      'NativeModule internal/perf/utils',
      'NativeModule internal/event_target',
      'NativeModule timers',
      'NativeModule internal/abort_controller',
      'NativeModule internal/streams/utils',
      'NativeModule internal/streams/end-of-stream',
      'NativeModule internal/streams/operators',
      'NativeModule internal/streams/destroy',
      'NativeModule internal/streams/legacy',
      'NativeModule internal/streams/add-abort-signal',
      'NativeModule internal/streams/buffer_list',
      'NativeModule internal/streams/state',
      'NativeModule string_decoder',
      'NativeModule internal/streams/from',
      'NativeModule internal/streams/readable',
      'NativeModule internal/streams/writable',
      'NativeModule internal/streams/duplex',
      'NativeModule internal/streams/pipeline',
      'NativeModule internal/streams/compose',
      'NativeModule stream/promises',
      'NativeModule internal/streams/transform',
      'NativeModule internal/streams/passthrough',
      'NativeModule stream',
      'NativeModule internal/worker/io',
      'NativeModule internal/structured_clone',
      'Internal Binding trace_events',
      'NativeModule path',
      'NativeModule internal/process/execution',
      'NativeModule internal/process/warning',
      'Internal Binding fs',
      'NativeModule internal/querystring',
      'NativeModule querystring',
      'Internal Binding url',
      'NativeModule internal/url',
      'NativeModule internal/fs/utils',
      'Internal Binding fs_dir',
      'NativeModule internal/fs/dir',
      'Internal Binding fs_event_wrap',
      'Internal Binding uv',
      'NativeModule internal/fs/watchers',
      'NativeModule internal/fs/read_file_context',
      'NativeModule fs',
      'Internal Binding serdes',
      'Internal Binding profiler',
      'Internal Binding heap_utils',
      'Internal Binding stream_wrap',
      'NativeModule internal/stream_base_commons',
      'NativeModule internal/heap_utils',
      'Internal Binding v8',
      'NativeModule v8',
      'Internal Binding contextify',
      'NativeModule vm',
      'NativeModule internal/idna',
      'NativeModule url',
      'Internal Binding options',
      ... 130 more items
    ],
      binding: [Function: binding],
        _linkedBinding: [Function: _linkedBinding],
          _events: [Object: null prototype] {
    newListener: [Function: startListeningIfSignal],
      removeListener: [Function: stopListeningIfSignal],
        warning: [Function: onWarning],
          SIGWINCH: [
            [Function: refreshStdoutOnSigWinch],
            [Function: refreshStderrOnSigWinch]
          ]
  },
  _eventsCount: 4,
    _maxListeners: undefined,
      domain: null,
        _exiting: false,
          config: [Getter / Setter],
            dlopen: [Function: dlopen],
              uptime: [Function: uptime],
                _getActiveRequests: [Function: _getActiveRequests],
                  _getActiveHandles: [Function: _getActiveHandles],
                    getActiveResourcesInfo: [Function(anonymous)],
                      reallyExit: [Function: reallyExit],
                        _kill: [Function: _kill],
                          cpuUsage: [Function: cpuUsage],
                            resourceUsage: [Function: resourceUsage],
                              memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
  kill: [Function: kill],
    exit: [Function: exit],
      hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
  openStdin: [Function(anonymous)],
    allowedNodeEnvironmentFlags: NodeEnvironmentFlagsSet(0)[Set] {
    '--icu-data-dir',
      '--title',
      '--use-largepages',
      '--trace-tls',
      '--no-trace-tls',
      '--trace-event-categories',
      '--conditions',
      '--trace-event-file-pattern',
      '--v8-pool-size',
      '--force-context-aware',
      '--no-force-context-aware',
      '--disallow-code-generation-from-strings',
      '--zero-fill-buffers',
      '--no-zero-fill-buffers',
      '--trace-sync-io',
      '--no-trace-sync-io',
      '--trace-atomics-wait',
      '--no-trace-atomics-wait',
      '--report-dir',
      '--disable-proto',
      '--experimental-worker',
      '--diagnostic-dir',
      '--node-snapshot',
      '--no-node-snapshot',
      '--debug-arraybuffer-allocations',
      '--no-debug-arraybuffer-allocations',
      '--pending-deprecation',
      '--no-pending-deprecation',
      '--use-bundled-ca',
      '--no-use-bundled-ca',
      '--report-filename',
      '--report-compact',
      '--no-report-compact',
      '--report-on-fatalerror',
      '--no-report-on-fatalerror',
      '--perf-prof',
      '--report-signal',
      '--preserve-symlinks-main',
      '--no-preserve-symlinks-main',
      '--addons',
      '--no-addons',
      '--openssl-config',
      '--tls-cipher-list',
      '--use-openssl-ca',
      '--no-use-openssl-ca',
      '--node-memory-debug',
      '--enable-fips',
      '--no-enable-fips',
      '--force-fips',
      '--no-force-fips',
      '--secure-heap',
      '--secure-heap-min',
      '--openssl-legacy-provider',
      '--no-openssl-legacy-provider',
      '--trace-sigint',
      '--no-trace-sigint',
      '--track-heap-objects',
      '--no-track-heap-objects',
      '--warnings',
      '--no-warnings',
      '--experimental-repl-await',
      '--no-experimental-repl-await',
      '--experimental-json-modules',
      '--perf-prof-unwinding-info',
      '--experimental-network-imports',
      '--no-experimental-network-imports',
      '--unhandled-rejections',
      '--abort-on-uncaught-exception',
      '--interpreted-frames-native-stack',
      '--perf-basic-prof-only-functions',
      '--max-old-space-size',
      '--perf-basic-prof',
      '--stack-trace-limit',
      '--jitless',
      '--experimental-top-level-await',
      '--require',
      '--huge-max-old-generation-size',
      '--report-uncaught-exception',
      '--no-report-uncaught-exception',
      '--report-on-signal',
      '--no-report-on-signal',
      '--experimental-global-webcrypto',
      '--no-experimental-global-webcrypto',
      '--verify-base-objects',
      '--no-verify-base-objects',
      '--experimental-vm-modules',
      '--no-experimental-vm-modules',
      '--dns-result-order',
      '--experimental-abortcontroller',
      '--experimental-policy',
      '--enable-source-maps',
      '--no-enable-source-maps',
      '--experimental-fetch',
      '--no-experimental-fetch',
      '--experimental-loader',
      '--experimental-modules',
      '--experimental-wasm-modules',
      '--no-experimental-wasm-modules',
      '--experimental-import-meta-resolve',
      '--no-experimental-import-meta-resolve',
      '--policy-integrity',
      '--experimental-report',
      '--experimental-wasi-unstable-preview1',
      '--no-experimental-wasi-unstable-preview1',
      '--trace-uncaught',
      '--no-trace-uncaught',
      '--insecure-http-parser',
      '--no-insecure-http-parser',
      '--force-async-hooks-checks',
      '--no-force-async-hooks-checks',
      '--frozen-intrinsics',
      '--no-frozen-intrinsics',
      '--input-type',
      '--heapsnapshot-signal',
      '--heapsnapshot-near-heap-limit',
      '--http-parser',
      '--experimental-specifier-resolution',
      '--deprecation',
      '--no-deprecation',
      '--trace-exit',
      '--no-trace-exit',
      '--global-search-paths',
      '--no-global-search-paths',
      '--preserve-symlinks',
      '--no-preserve-symlinks',
      '--test-only',
      '--no-test-only',
      '--throw-deprecation',
      '--no-throw-deprecation',
      '--max-http-header-size',
      '--redirect-warnings',
      '--trace-deprecation',
      '--no-trace-deprecation',
      '--trace-warnings',
      '--no-trace-warnings',
      '--extra-info-on-fatal-exception',
      '--no-extra-info-on-fatal-exception',
      '--inspect',
      '--no-inspect',
      '--napi-modules',
      '--tls-keylog',
      '--tls-min-v1.0',
      '--no-tls-min-v1.0',
      '--tls-min-v1.1',
      '--no-tls-min-v1.1',
      '--tls-min-v1.2',
      '--no-tls-min-v1.2',
      '--tls-min-v1.3',
      '--no-tls-min-v1.3',
      '--tls-max-v1.2',
      '--no-tls-max-v1.2',
      '--tls-max-v1.3',
      '--no-tls-max-v1.3',
      '--inspect-port',
      '--inspect-brk',
      '--no-inspect-brk',
      '--inspect-publish-uid',
      '--debug-port',
      '--trace-events-enabled',
      '--report-directory',
      '-C',
      '--loader',
      '--es-module-specifier-resolution',
      '--prof-process',
      '-r',
      [Symbol(internal properties)]: { array: [Array], set: [Set] }
  },
  assert: [Function: deprecated],
    features: {
    inspector: true,
      debug: false,
        uv: true,
          ipv6: true,
            tls_alpn: true,
              tls_sni: true,
                tls_ocsp: true,
                  tls: true,
                    cached_builtins: [Getter]
  },
  _fatalException: [Function(anonymous)],
    setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
      hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
        emitWarning: [Function: emitWarning],
          nextTick: [Function: nextTick],
            _tickCallback: [Function: runNextTicks],
              _debugProcess: [Function: _debugProcess],
                _debugEnd: [Function: _debugEnd],
                  _startProfilerIdleNotifier: [Function(anonymous)],
                    _stopProfilerIdleNotifier: [Function(anonymous)],
                      stdout: [Getter],
                        stdin: [Getter],
                          stderr: [Getter],
                            abort: [Function: abort],
                              umask: [Function: wrappedUmask],
                                chdir: [Function(anonymous)],
                                  cwd: [Function: wrappedCwd],
                                    env: {
    ALLUSERSPROFILE: 'C:\\ProgramData',
      APPDATA: 'C:\\Users\\Administrator\\AppData\\Roaming',
        CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\LOCAL\\crashpad_12408_DYWBWOBBCXTZABED',
          COLOR: '1',
            COLORTERM: 'truecolor',
              CommonProgramFiles: 'C:\\Program Files\\Common Files',
                'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
                  CommonProgramW6432: 'C:\\Program Files\\Common Files',
                    COMPUTERNAME: 'BF-202103171158',
                      ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
                        DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
                          EDITOR: 'notepad.exe',
                            GIT_ASKPASS: 'd:\\Program Files\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
                              HOME: 'C:\\Users\\Administrator',
                                HOMEDRIVE: 'C:',
                                  HOMEPATH: '\\Users\\Administrator',
                                    INIT_CWD: 'E:\\web-note\\note\\monorepo\\v',
                                      LANG: 'en_US.UTF-8',
                                        LOCALAPPDATA: 'C:\\Users\\Administrator\\AppData\\Local',
                                          LOGONSERVER: '\\\\BF-202103171158',
                                            NODE: 'D:\\nvm\\nodejs\\node.exe',
                                              NODE_EXE: 'D:\\nvm\\nodejs\\\\node.exe',
                                                NODE_OPTIONS: '--require "d:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http',
                                                  NPM_CLI_JS: 'D:\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
                                                    npm_command: 'run-script',
                                                      npm_config_cache: 'C:\\Users\\Administrator\\AppData\\Local\\npm-cache',
                                                        npm_config_globalconfig: 'D:\\nvm\\nodejs\\etc\\npmrc',
                                                          npm_config_global_prefix: 'D:\\nvm\\nodejs',
                                                            npm_config_init_module: 'C:\\Users\\Administrator\\.npm-init.js',
                                                              npm_config_local_prefix: 'E:\\web-note\\note\\monorepo\\v',
                                                                npm_config_metrics_registry: 'https://registry.npm.taobao.org/',
                                                                  npm_config_node_gyp: 'D:\\nvm\\v18.1.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
                                                                    npm_config_noproxy: '',
                                                                      npm_config_prefix: 'D:\\nvm\\nodejs',
                                                                        npm_config_registry: 'https://registry.npm.taobao.org/',
                                                                          npm_config_sass_binary_site: 'https://npm.taobao.org/mirrors/node-sass/',
                                                                            npm_config_strict_ssl: '',
                                                                              npm_config_userconfig: 'C:\\Users\\Administrator\\.npmrc',
                                                                                npm_config_user_agent: 'npm/8.8.0 node/v18.1.0 win32 x64 workspaces/false',
                                                                                  npm_execpath: 'D:\\nvm\\v18.1.0\\node_modules\\npm\\bin\\npm-cli.js',
                                                                                    npm_lifecycle_event: 'dev',
                                                                                      npm_lifecycle_script: 'node scripts/dev',
                                                                                        npm_node_execpath: 'D:\\nvm\\nodejs\\node.exe',
                                                                                          npm_package_json: 'E:\\web-note\\note\\monorepo\\v\\package.json',
                                                                                            npm_package_name: 'v~3',
                                                                                              npm_package_version: '1.0.0',
                                                                                                NPM_PREFIX_NPM_CLI_JS: 'D:\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
                                                                                                  NUMBER_OF_PROCESSORS: '12',
                                                                                                    NVM_HOME: 'D:\\nvm',
                                                                                                      NVM_SYMLINK: 'D:\\nvm\\nodejs',
                                                                                                        OneDrive: 'C:\\Users\\Administrator\\OneDrive',
                                                                                                          ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
                                                                                                            OS: 'Windows_NT',
                                                                                                              Path: 'E:\\web-note\\note\\monorepo\\v\\node_modules\\.bin;E:\\web-note\\note\\monorepo\\node_modules\\.bin;E:\\web-note\\note\\node_modules\\.bin;E:\\web-note\\node_modules\\.bin;E:\\node_modules\\.bin;D:\\nvm\\v18.1.0\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;D:\\Program Files\\ruby\\Ruby27-x64\\bin;D:\\Program Files\\python\\;D:\\Program Files\\python\\Scripts;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Program Files\\Microsoft VS Code\\bin;D:\\Program Files (x86)\\WinSCP\\;D:\\Program Files\\cmder;D:\\Program Files\\Git\\cmd;D:\\nvm;D:\\nvm\\nodejs;D:\\Program Files\\mysql\\bin;;D:\\Program Files (x86)\\Tencent\\微信web开发者工具\\dll;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Program Files\\mysql\\bin;',
                                                                                                                PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
                                                                                                                  PROCESSOR_ARCHITECTURE: 'AMD64',
                                                                                                                    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 165 Stepping 3, GenuineIntel',
                                                                                                                      PROCESSOR_LEVEL: '6',
                                                                                                                        PROCESSOR_REVISION: 'a503',
                                                                                                                          ProgramData: 'C:\\ProgramData',
                                                                                                                            ProgramFiles: 'C:\\Program Files',
                                                                                                                              'ProgramFiles(x86)': 'C:\\Program Files (x86)',
                                                                                                                                ProgramW6432: 'C:\\Program Files',
                                                                                                                                  PROMPT: '$P$G',
                                                                                                                                    PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
                                                                                                                                      PUBLIC: 'C:\\Users\\Public',
                                                                                                                                        RUBYOPT: '-Eutf-8',
                                                                                                                                          SESSIONNAME: 'Console',
                                                                                                                                            SystemDrive: 'C:',
                                                                                                                                              SystemRoot: 'C:\\WINDOWS',
                                                                                                                                                TEMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
                                                                                                                                                  TERM_PROGRAM: 'vscode',
                                                                                                                                                    TERM_PROGRAM_VERSION: '1.75.1',
                                                                                                                                                      TMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
                                                                                                                                                        USERDOMAIN: 'BF-202103171158',
                                                                                                                                                          USERDOMAIN_ROAMINGPROFILE: 'BF-202103171158',
                                                                                                                                                            USERNAME: 'Administrator',
                                                                                                                                                              USERPROFILE: 'C:\\Users\\Administrator',
                                                                                                                                                                VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
                                                                                                                                                                  VSCODE_GIT_ASKPASS_MAIN: 'd:\\Program Files\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
                                                                                                                                                                    VSCODE_GIT_ASKPASS_NODE: 'D:\\Program Files\\Microsoft VS Code\\Code.exe',
                                                                                                                                                                      VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-ff40b3d907-sock',
                                                                                                                                                                        VSCODE_INSPECTOR_OPTIONS: '{"inspectorIpc":"\\\\\\\\.\\\\pipe\\\\node-cdp.23160-0.sock","deferredMode":false,"waitForDebugger":"","execPath":"D:\\\\nvm\\\\nodejs\\\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","openerId":"a7e8089354f592f6bf1f06a3"}',
                                                                                                                                                                          windir: 'C:\\WINDOWS',
                                                                                                                                                                            ZES_ENABLE_SYSMAN: '1'
  },
  title: 'npm run dev',
    argv: [
      'D:\\nvm\\nodejs\\node.exe',
      'E:\\web-note\\note\\monorepo\\v\\scripts\\dev'
    ],
      execArgv: [],
        pid: 19416,
          ppid: 22704,
            execPath: 'D:\\nvm\\nodejs\\node.exe',
              debugPort: 55843,
                argv0: 'node',
                  exitCode: undefined,
                    _preload_modules: [
                      'd:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
                    ],
                      report: [Getter],
                        setSourceMapsEnabled: [Function: setSourceMapsEnabled],
                          mainModule: Module {
    id: '.',
      path: 'E:\\web-note\\note\\monorepo\\v\\scripts',
        exports: { },
    filename: 'E:\\web-note\\note\\monorepo\\v\\scripts\\dev.js',
      loaded: true,
        children: [],
          paths: [
            'E:\\web-note\\note\\monorepo\\v\\scripts\\node_modules',
            'E:\\web-note\\note\\monorepo\\v\\node_modules',
            'E:\\web-note\\note\\monorepo\\node_modules',
            'E:\\web-note\\note\\node_modules',
            'E:\\web-note\\node_modules',